In [2]:
#1. Import the numpy package under the name np
import numpy as np

In [3]:
#2. Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())

1.21.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,AVX512C

In [231]:
#3. Create a null vector of size 10
X=np.zeros(10)
X

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [233]:
#4. How to find the memory size of any array
x=np.zeros(10)
i=x.itemsize
print(x.itemsize*len(x))

80


In [234]:
#5. How to get the documentation of the numpy add function from the command line?
python -c "import numpy as np; np.info(np.add)"

SyntaxError: invalid syntax (Temp/ipykernel_6132/3530710197.py, line 2)

In [7]:
#6. Create a null vector of size 10 but the fifth value which is 1
A=np.zeros(10)
A[4]=1
A

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
#7. Create a vector with values ranging from 10 to 49
B=np.arange(10,50)
B

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
# 8. Reverse a vector (first element becomes last)
C=np.arange(1,11)
C=C[::-1]
C

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [10]:
#9. Create a 3x3 matrix with values ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0] 
x=np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

In [12]:
#11. Create a 3x3 identity matrix
x11=np.identity(3)
x11

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#12. Create a 3x3x3 array with random values
x=np.random.random((3,3,3))
x

array([[[0.60759185, 0.62646083, 0.20497507],
        [0.90286197, 0.02910472, 0.64883642],
        [0.34199358, 0.30449892, 0.37826732]],

       [[0.54325764, 0.99698951, 0.74014432],
        [0.62084274, 0.98826239, 0.52384534],
        [0.58700062, 0.1484248 , 0.09510429]],

       [[0.46139619, 0.88599564, 0.37576782],
        [0.05034247, 0.14359772, 0.18155522],
        [0.71863844, 0.08177096, 0.36288968]]])

In [14]:
#13. Create a 10x10 array with random values and find the minimum and maximum values
x=np.random.random((10,10))
print("x_min=",x.min())
print("x_max=",x.max())

x_min= 0.01368227215732254
x_max= 0.9982048325429993


In [15]:
#14. Create a random vector of size 30 and find the mean value
x=np.random.random(30)
x.mean()

0.4637183528363894

In [16]:
#15. Create a 2d array with 1 on the border and 0 inside 
x=np.ones((5,5))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#16. How to add a border (filled with 0's) around an existing array?
x=np.ones((5,5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [18]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
x = np.diag(np.arange(1,5), k = -1)
print (x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern
x=np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [20]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
x=np.random.random((6,7,8))
y=np.unravel_index(100, (6,7,8))
y

(1, 5, 4)

In [21]:
#21. Create a checkerboard 8x8 matrix using the tile function 
x=[[0,1],[1,0]]
x=np.tile(x,(4,4))
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [22]:
#22. Normalize a 5x5 random matrix
x=np.random.random((5,5))
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
x

array([[0.79396846, 0.07697387, 0.        , 0.70491821, 0.30460727],
       [1.        , 0.06576447, 0.0467245 , 0.97271373, 0.57468621],
       [0.98216498, 0.34255896, 0.83016477, 0.07775154, 0.34351303],
       [0.49871103, 0.86717692, 0.47307651, 0.08489294, 0.34111513],
       [0.12692981, 0.23036138, 0.54074701, 0.34635031, 0.53416158]])

In [23]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
x=['r','g','b','a']
for i in x:
    color = np.dtype([(i,np.unicode_,  1)])
                  

In [24]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a=np.random.random((5,3))
b=np.random.random((3,2))
Z= np.dot(a,b)
Z

array([[0.47091995, 0.61006901],
       [0.1750515 , 0.59554986],
       [0.13935759, 0.59273774],
       [0.35067999, 0.58762769],
       [0.30978165, 0.65774342]])

In [26]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place
x = np.arange(11)
x[(3 < x) & (x <= 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [235]:
#26. What is the output of the following script? 
#9
#10

In [236]:
#27. Consider an integer vector Z, which of these expressions are legal? 
#Z**Z
#Z <- Z
#1j*Z
#Z/1/1
#Z<Z>Z

In [237]:
#28. What are the result of the following expressions?
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


In [34]:
#29. How to round away from zero a float array ?
x=np.random.random((1,4))
print(x)
print(np.round(x,0))

[[0.40422093 0.88306339 0.13803169 0.18533503]]
[[0. 1. 0. 0.]]


In [36]:
#30. How to find common values between two arrays?
x=np.array([1,2,3,6,8])
y=np.array([2,3,90,11])
print(np.intersect1d(x,y))

[2 3]


In [38]:
#31. How to ignore all numpy warnings (not recommended)?(ask)
defaults = np.seterr(all="ignore")


In [41]:
#32. Is the following expressions true?
#false
#nan not equal to 1j

In [44]:
#33. How to get the dates of yesterday, today and tomorrow?
y = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
t     = np.datetime64('today', 'D')
to  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Today: ",t)
print("Yestraday: ",y)
print("Tomorrow: ",to)

Today:  2021-09-10
Yestraday:  2021-09-09
Tomorrow:  2021-09-11


In [47]:
#34. How to get all the dates corresponding to the month of July 2016?
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [62]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?
A=np.arange(1,10)
print(A)
B=np.ones((9),dtype=int)
print(B)
print(np.multiply(np.add(A,B),np.divide(np.negative(A),2)))

[1 2 3 4 5 6 7 8 9]
[1 1 1 1 1 1 1 1 1]
[ -1.  -3.  -6. -10. -15. -21. -28. -36. -45.]


In [70]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods
Z = np.random.uniform(0,5,5)
print(Z)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))
print(Z - Z%1)
print(Z // 1)

[3.94366432 3.60694211 2.56225464 0.79463711 0.79581693]
[3. 3. 2. 0. 0.]
[3 3 2 0 0]
[3. 3. 2. 0. 0.]
[3. 3. 2. 0. 0.]
[3. 3. 2. 0. 0.]


In [77]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4 
x = np.zeros((5,5))
print(x)
x += np.arange(5)
x

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [78]:
#38. Consider a generator function that generates 10 integers and use it to build an array
def generator():
   for n in range(10):
       yield n
x = np.fromiter(generator(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [79]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
x = np.linspace(0,1,12,endpoint=True)[1:-1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [81]:
#40. Create a random vector of size 10 and sort it 
x = np.random.random(10)
x.sort()
x

array([0.08092737, 0.10829904, 0.36806287, 0.56305537, 0.59147689,
       0.67029905, 0.72730741, 0.82692006, 0.82757597, 0.86434221])

In [85]:
#41. How to sum a small array faster than np.sum?
x = np.arange(10)
print(x)
np.add.reduce(x)

[0 1 2 3 4 5 6 7 8 9]


45

In [89]:
#
A = np.random.randint(0,10,5)
B = np.random.randint(0,10,5)
print(np.array_equal(A,B))

False


In [93]:
#43. Make an array immutable (read-only)
x = np.zeros(10)
x.flags.writeable = False

In [102]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
test= np.random.random((10,2))
print(z)
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[[0.39138667 0.5723342 ]
 [0.4043412  0.2564548 ]
 [0.72624608 0.65845774]
 [0.32384375 0.14481239]
 [0.81127906 0.04349861]
 [0.69019711 0.01309302]
 [0.08613728 0.36423927]
 [0.95727135 0.10146412]
 [0.98508661 0.13787884]
 [0.14879184 0.74989007]]
[0.69336135 0.47881194 0.98030605 0.35474696 0.81244436 0.69032129
 0.37428582 0.96263358 0.994689   0.76450908]
[0.97099656 0.56522582 0.7364821  0.42049591 0.05356603 0.01896769
 1.33857715 0.10559878 0.13906281 1.37492219]


In [99]:
#45. Create random vector of size 10 and replace the maximum value by 0
x = np.random.randint(0,10,10)
print(x)
x[x.argmax()] = 0
x

[0 0 4 1 0 9 9 5 0 5]


array([0, 0, 4, 1, 0, 0, 9, 5, 0, 5])

In [106]:
#Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
test = np.zeros((5,5), [('x',float),('y',float)])
test['x'], test['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(test)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [109]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [110]:
#17. What is the result of the following expression?
#nan
#False
#False
#nan
#True
#False

In [111]:
#48. Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [115]:
#49. How to print all the values of an array?
np.set_printoptions(threshold=float("inf"))
x= np.random.random((10,10))
print(x)

[[1.55962866e-01 2.52347056e-01 8.97124089e-01 5.36597472e-01
  5.09910312e-01 8.76236339e-02 7.73115058e-01 5.45728760e-02
  9.96325581e-01 7.27128125e-01]
 [1.14504305e-01 2.22069640e-01 1.11739399e-01 7.40485790e-01
  3.91837080e-01 4.16693394e-01 3.88596396e-01 2.44332323e-01
  6.14085712e-01 6.08460711e-01]
 [4.50480952e-01 7.85018532e-01 1.18610227e-01 4.77730723e-01
  2.48389231e-01 6.84414516e-01 3.25908603e-01 7.09495642e-01
  3.69521800e-01 4.34157522e-01]
 [2.02766966e-02 6.29812658e-01 5.50141449e-01 5.69577053e-04
  8.27798054e-01 3.94269745e-01 8.82073023e-02 3.75362511e-01
  3.91272027e-02 9.43159597e-01]
 [2.04499315e-01 8.36049236e-01 8.31692176e-01 4.52998682e-01
  3.98622001e-01 3.39792753e-01 8.75857641e-01 2.76732411e-01
  3.24424604e-01 4.39546619e-01]
 [2.49524839e-01 1.15771854e-01 7.50060515e-01 5.33956453e-01
  3.36944468e-01 6.01607228e-01 4.99860270e-01 7.45214443e-01
  7.82556632e-01 7.34569976e-01]
 [8.99433774e-01 2.52203921e-01 2.40995191e-01 9.51540600e

In [119]:
#50. How to find the closest value (to a given scalar) in a vector?
x = np.arange(10)
y = np.random.uniform(0,10)
index = (np.abs(x-y)).argmin()
print(x[index])

8


In [238]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b)
Z = np.zeros(10, [ ('position', [ ('x', float),('y', float)]), ('color',    [ ('r', float),('g', float), ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [127]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances
test = np.random.random((100,2))
X,Y = np.atleast_2d(test[:,0], test[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.29725819 0.3890437  0.63819171 0.26043286 0.21165004
  0.27020694 0.74787529 0.3265219  0.12675126 0.52195439 0.67446873
  0.65302796 0.30746992 0.68728881 0.84658734 0.38814416 0.27275194
  0.04790151 0.43512978 0.26916117 0.47755032 0.51252758 0.59224586
  0.56959335 0.61845788 0.06887118 0.19742561 0.29209681 0.43536073
  0.5123069  0.48326703 0.41588615 0.3668168  0.17503032 0.15934789
  0.66505793 0.36035715 0.22953479 0.39326242 0.62294359 0.09497566
  0.22343397 0.34700544 0.50104662 0.10643287 0.58822165 0.2477959
  0.34311539 0.49484056 0.29419436 0.1515671  0.59269307 0.37877166
  0.34510029 0.79311866 0.25111687 0.17552873 0.61547867 0.28901384
  0.61589221 0.3812194  0.3803205  0.49985043 0.68465184 0.25606252
  0.43378334 0.38580825 0.74806199 0.34128568 0.24511836 0.42696601
  0.56529049 0.48349112 0.16831684 0.4945913  0.04769304 0.41577624
  0.44608756 0.38328701 0.48554886 0.57488422 0.59495703 0.64982104
  0.31757032 0.22213503 0.5815181  0.20395923 0.3

In [144]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
x=np.array([1.2,3.4,5.6]).astype(np.float32)
print(x.dtype)

y = np.array(x, dtype ='int32' )
print(y.dtype)

float32
int32


In [239]:
#54. How to read the following file?
from io import StringIO

chars = StringIO('''1, 2, 3, 4, 5

                    6,  ,  , 7, 8

                     ,  , 9, 10, 11
''')
r = np.genfromtxt(chars, delimiter=",", dtype=np.int32,filling_values=0)
print(r)

[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


In [147]:
#55. What is the equivalent of enumerate for numpy arrays?
x = np.array([[1, 2], [3, 4]])
for index, i in np.ndenumerate(x):
    print(index, i)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [149]:
#56. Generate a generic 2D Gaussian-like array
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [151]:
#57. How to randomly place p elements in a 2D array?
x = np.ones((5,5))
np.put(x, np.random.choice(range(5*5), 3, replace=False),4)
print (x)

[[4. 1. 1. 1. 4.]
 [4. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [153]:
#58. Subtract the mean of each row of a matrix
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[ 1.8 -1.2 -1.2 -1.2  1.8]
 [ 2.4 -0.6 -0.6 -0.6 -0.6]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0. ]]


In [160]:
#59. How to sort an array by the nth column?
#n=3
x = np.array([[9, 2, 3],[4, 5, 6],[7, 0, 5]])
print(x[x[:,2].argsort()])

[[9 2 3]
 [7 0 5]
 [4 5 6]]


In [163]:
#60. How to tell if a given 2D array has null columns?
print((~y.any(axis=0)).any())

False


In [167]:
#61. Find the nearest value from a given value in an array 
y = np.random.uniform(0,1,10)
m = y.flat[np.abs(y - 1).argmin()]
print(m)

0.9702953952171752


In [169]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
x = np.arange(3).reshape(1,3)
y = np.arange(3).reshape(3,1)
t = np.nditer([A,B,None])
for i,j,k in t: k[...] = i + j
print(t.operands[2])

[15  5 15  8  5]


In [240]:
#63. Create an array class that has a name attribute
class Array(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = Array(np.arange(8), "name_given")
print (Z.name)

name_given


In [176]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
x = np.ones(10)
y = np.random.randint(0,len(x),20)
np.add.at(x, y, 1)
print(x)

[3. 2. 3. 1. 7. 2. 5. 2. 4. 1.]


In [179]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)
X = [1,2,3,1,5,6]
I = [1,3,0,3,1,1]
F = np.bincount(I,X)
print(F)

[ 3. 12.  0.  3.]


In [241]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


In [189]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once? 
x =  np.random.randint(0,10,(3,3,3,3))
sum = x.sum(axis=(-2,-1))
print(sum)

[[45 29 46]
 [22 38 46]
 [47 45 59]]


In [242]:
#68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?
D = np.random.uniform(0,1,10)
S = np.random.randint(0,10,10)
sums = np.bincount(S, weights=D)
counts = np.bincount(S)
D_means = sums / counts
print(D_means)

[0.22735474        nan 0.19104046        nan 0.50948037 0.62876057
        nan 0.2356853  0.48816897 0.89629322]


In [194]:
#69. How to get the diagonal of a dot product?
x=np.array([[2,4],[2,4],[4,6]])
y=np.array([[2,4,5],[3,5,6]])
A=np.dot(x,y)
print(A)
np.diag(np.dot(x, y))

[[16 28 34]
 [16 28 34]
 [26 46 56]]


array([16, 28, 56])

In [195]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
x = np.array([1,2,3,4,5])
y = np.zeros(len(x) + (len(x)-1)*(3))
y[::3+1] = x
print(y)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [196]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
A = np.random.random((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[0.26343308 0.39350052 1.01447515]
  [0.23767596 1.31436011 0.34135078]
  [0.17869007 1.06730609 1.21695531]
  [0.563061   1.77439987 0.4096798 ]
  [1.09618649 1.64800239 0.78029545]]

 [[1.38781084 0.90827699 0.69176216]
  [1.89316079 0.76497052 0.08248671]
  [1.20334926 0.10797206 1.4128301 ]
  [0.62878517 0.19605762 0.89863248]
  [1.89504896 1.89945359 0.86865351]]

 [[0.15315273 1.95940347 1.60120139]
  [0.66551211 1.10744697 1.22333879]
  [0.94471278 1.27297636 1.70266049]
  [1.97354647 1.27819095 0.79292813]
  [1.5358656  0.64738681 0.76025706]]

 [[1.10141399 0.14623213 0.17210833]
  [0.79976914 1.20537355 0.71423246]
  [1.02378603 0.84895531 0.53196996]
  [1.9845759  0.1797335  0.96369344]
  [0.44790892 1.44361189 0.74445568]]

 [[0.2994038  1.18369444 1.78249243]
  [0.90456311 1.10790144 0.04124324]
  [1.55253595 0.95222524 1.61807791]
  [1.02426124 0.1143863  0.81716773]
  [0.72136072 1.87020719 0.87351135]]]


In [198]:
#72. How to swap two rows of an array?
x = np.arange(4).reshape(2,2)
x[[0,1]] = x[[1,0]]
print(x)

[[2 3]
 [0 1]]


In [246]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles
f = np.random.randint(0,100,(10,3))
F = np.roll(f.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
l = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
l = np.unique(l)
print(l)

[( 0, 23) ( 0, 98) ( 8, 38) ( 8, 77) (10, 89) (10, 91) (13, 62) (13, 63)
 (14, 33) (14, 38) (15, 23) (15, 75) (18, 41) (18, 73) (23, 75) (23, 98)
 (28, 56) (28, 58) (33, 38) (38, 77) (41, 73) (44, 50) (44, 81) (50, 81)
 (55, 62) (55, 80) (56, 58) (62, 63) (62, 80) (89, 91)]


In [200]:
#74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?
C = np.bincount([0,0,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 0 2 3 4 4 6]


In [201]:
#75. How to compute averages using a sliding window over an array?
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [204]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
a=np.arange(10)
window=3
shape = (a.size - window + 1, window)
strides = (a.itemsize, a.itemsize)
s=np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
print(s)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [208]:
#77. How to negate a boolean, or to change the sign of a float inplace?
Z = [True,False]
print(np.logical_not(Z))

Z = [1,-2]
np.negative(Z)

[False  True]


array([-1,  2])

In [247]:
#78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?
def distance(P0, P1, p):
    len1 = P1 - P0
    L = (len1**2).sum(axis=1)
    M = -((P0[:,0]-p[...,0])*len1[:,0] + (P0[:,1]-p[...,1])*len1[:,1]) / L
    M = M.reshape(len(M),1)
    N = P0 + M*len1 - p
    return np.sqrt((N**2).sum(axis=1))

a = np.random.uniform(-10,10,(10,2))
b = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(a, b, p))

[ 4.22093324 16.63949046 18.2770947   4.84604583 14.5181946   4.87628686
 15.8495479  12.3955275   9.28893358  9.81475718]


In [248]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?
P0 = np.random.uniform(-1, 1, (10,2))
P1 = np.random.uniform(-1, 1, (10,2))
p = np.random.uniform(-1, 1, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[6.65788718e-01 7.19773051e-01 7.73977016e-01 1.92332457e-01
  3.20994951e-01 3.54932180e-01 9.94808501e-01 5.09006875e-01
  7.20202342e-01 1.27136183e+00]
 [1.01495695e+00 3.92067895e-01 1.29429818e-01 4.47853873e-01
  4.68896422e-01 2.80327000e-01 3.64956832e-01 4.07843270e-01
  5.50859763e-01 6.61256324e-01]
 [1.01803614e+00 7.32923796e-01 4.09913490e-01 8.81176533e-02
  5.97700089e-01 8.35936583e-02 7.32546617e-01 2.53137755e-01
  8.34367464e-01 8.86502507e-01]
 [8.29415647e-03 4.99877177e-01 1.30855979e+00 5.22033060e-01
  2.80753025e-01 6.64850430e-01 1.28530560e+00 1.08578845e+00
  3.40277504e-01 1.87720450e+00]
 [8.73404179e-01 3.05606646e-01 2.08151661e-01 4.21439222e-01
  3.27591436e-01 2.58551802e-01 3.82229314e-01 5.46989304e-01
  4.37678007e-01 7.61451301e-01]
 [2.62427082e-01 2.33359670e-01 4.09924934e-01 4.83639349e-01
  3.43805159e-01 3.42774039e-01 2.76825725e-01 1.22175776e+00
  1.88289912e-01 1.08269379e+00]
 [3.61386323e-01 4.06902891e-01 8.37587716e-01 1.14206668e

In [249]:
#80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 5 3 5 9 3 8 8 4 0]
 [4 4 9 7 3 3 7 4 3 5]
 [1 7 2 5 1 6 3 6 6 3]
 [0 7 1 4 2 5 6 3 7 6]
 [4 3 5 6 4 4 3 1 2 4]
 [5 6 4 0 5 6 3 0 5 1]
 [3 0 2 6 7 6 0 9 8 5]
 [1 8 6 5 5 3 7 1 2 9]
 [0 4 2 1 5 3 8 1 5 1]
 [9 8 0 3 5 2 3 7 9 2]]
[[0 0 0 0 0]
 [0 8 5 3 5]
 [0 4 4 9 7]
 [0 1 7 2 5]
 [0 0 7 1 4]]


C:\Users\admin\AppData\Local\Temp/ipykernel_6132/3709699144.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


In [214]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [215]:
#82. Compute a matrix rank
np.linalg.matrix_rank(np.eye(5))

5

In [216]:
#83. How to find the most frequent value in an array?
Z = np.random.randint(0,5,10)
print(np.bincount(Z).argmax())

1


In [220]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
z = np.random.randint(0,5,(10,10))
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
c = np.lib.stride_tricks.as_strided(Z, shape=(i, j, 3,3), strides=Z.strides + Z.strides)
print(c)

[[[[0 0 2]
   [1 2 1]
   [0 2 4]]

  [[0 2 3]
   [2 1 3]
   [2 4 4]]

  [[2 3 3]
   [1 3 1]
   [4 4 0]]

  [[3 3 3]
   [3 1 4]
   [4 0 2]]

  [[3 3 3]
   [1 4 4]
   [0 2 2]]

  [[3 3 3]
   [4 4 0]
   [2 2 3]]

  [[3 3 2]
   [4 0 4]
   [2 3 1]]

  [[3 2 4]
   [0 4 4]
   [3 1 1]]]


 [[[1 2 1]
   [0 2 4]
   [2 0 0]]

  [[2 1 3]
   [2 4 4]
   [0 0 0]]

  [[1 3 1]
   [4 4 0]
   [0 0 3]]

  [[3 1 4]
   [4 0 2]
   [0 3 0]]

  [[1 4 4]
   [0 2 2]
   [3 0 4]]

  [[4 4 0]
   [2 2 3]
   [0 4 2]]

  [[4 0 4]
   [2 3 1]
   [4 2 4]]

  [[0 4 4]
   [3 1 1]
   [2 4 0]]]


 [[[0 2 4]
   [2 0 0]
   [4 3 4]]

  [[2 4 4]
   [0 0 0]
   [3 4 2]]

  [[4 4 0]
   [0 0 3]
   [4 2 0]]

  [[4 0 2]
   [0 3 0]
   [2 0 0]]

  [[0 2 2]
   [3 0 4]
   [0 0 4]]

  [[2 2 3]
   [0 4 2]
   [0 4 1]]

  [[2 3 1]
   [4 2 4]
   [4 1 4]]

  [[3 1 1]
   [2 4 0]
   [1 4 4]]]


 [[[2 0 0]
   [4 3 4]
   [3 0 0]]

  [[0 0 0]
   [3 4 2]
   [0 0 4]]

  [[0 0 3]
   [4 2 0]
   [0 4 1]]

  [[0 3 0]
   [2 0 0]
   [4 1 1]]

  [[3 0 4]
   

In [250]:
#Create a 2D array subclass such that Z[i,j] == Z[j,i]
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3  4  4  1  3]
 [ 4  2  1  7  8]
 [ 4  1  5 42  4]
 [ 1  7 42  4  8]
 [ 3  8  4  8  9]]


In [222]:
#86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))
p, n = 10, 20
A = np.ones((5,10,10))
B = np.ones((5,10,1))
S = np.tensordot(A, B, axes=[[0, 2], [0, 1]])
print(S)

[[50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]]


In [253]:
#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
x = np.ones((16,16))
k = 4
Sum = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], k), axis=0), np.arange(0, x.shape[1], k), axis=1)
print(Sum)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [224]:
#88. How to implement the Game of Life using numpy arrays?
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 1 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 1 1 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [230]:
#89. How to get the n largest values of an array
x=np.arange(100)
n=5
print (x[np.argsort(x)[-n:]])

[95 96 97 98 99]


In [256]:
#90Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)
arrays=np.array([[1, 2, 3], [4, 5], [6, 7]])
arrays = [np.asarray(a) for a in arrays]
shape = (len(x) for x in arrays)

ix = np.indices(shape, dtype=int)
ix = ix.reshape(len(arrays), -1).T

for n, arr in enumerate(arrays):
    ix[:, n] = arrays[n][ix[:, n]]

print(ix)



[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


C:\Users\admin\AppData\Local\Temp/ipykernel_6132/1647130827.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arrays=np.array([[1, 2, 3], [4, 5], [6, 7]])


In [261]:
#91. How to create a record array from a regular array?
x= np.array([("a", 1.0, 4),("b", 3.6, 2)])
R = np.core.records.fromarrays(x.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[(b'a', 1. , 4) (b'b', 3.6, 2)]


In [263]:
#92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods
Z = np.random.rand(int(5e7))
y= np.power(x,3)
z= x*x*x
g= np.einsum('i,i,i->i',x,x,x)

In [266]:
#93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?
A = np.random.randint(0,3,(8,3))
B = np.random.randint(0,3,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 5 7]


In [268]:
#94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])
x = np.random.randint(0,5,(10,3))
print(x)
E = np.all(x[:,1:] == x[:,:-1], axis=1)
U = x[~E]
U = x[x.max(axis=1) != x.min(axis=1),:]
print(U)

[[1 2 2]
 [2 0 1]
 [3 2 1]
 [3 4 0]
 [2 4 3]
 [4 3 4]
 [0 3 2]
 [3 0 1]
 [3 0 0]
 [0 1 4]]
[[1 2 2]
 [2 0 1]
 [3 2 1]
 [3 4 0]
 [2 4 3]
 [4 3 4]
 [0 3 2]
 [3 0 1]
 [3 0 0]
 [0 1 4]]


In [269]:
#95. Convert a vector of ints into a matrix binary representation
I = np.array([0, 1, 2, 3, 4, 5, 6, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 1 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [274]:
#96. Given a two dimensional array, how to extract unique rows?
A=np.array([[1,1,1],[0,1,0],[2,2,2],[2,2,2]])
B = np.unique(A, axis=0)
print(B)

[[0 1 0]
 [1 1 1]
 [2 2 2]]


In [275]:
#97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function
A = np.random.uniform(0,1,5)
B = np.random.uniform(0,1,5)
# np.sum(A)
np.einsum('i->', A)   
# A * B
np.einsum('i,i->i', A, B) 
 # np.inner(A, B)
np.einsum('i,i', A, B)  
# np.outer(A, B)
np.einsum('i,j->ij', A, B)    

array([[0.06993332, 0.09023937, 0.08669572, 0.15700088, 0.06846037],
       [0.37895291, 0.48898687, 0.46978463, 0.85075246, 0.37097135],
       [0.4179635 , 0.53932469, 0.51814572, 0.93833156, 0.40916029],
       [0.39970346, 0.5157626 , 0.4955089 , 0.89733761, 0.39128485],
       [0.24659311, 0.31819466, 0.30569934, 0.5536036 , 0.24139933]])

In [277]:
#98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples
phi = np.arange(0, 10*np.pi, 0.1)
x = 1*phi*np.cos(phi)
y = 1*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [283]:
#999. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n
X = np.asarray([[1.0, 3.0, 2.0, 8.0],[2.0, 0.0, 2.0, 0.0],[5.5, 6.5, 0.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 2. 0.]]


In [284]:
#100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).
X = np.random.randn(100) 
N = 1000 
d = np.random.randint(0, X.size, (N, X.size))
m = X[d].mean(axis=1)
c = np.percentile(m, [2.5, 97.5])
print(c)

[-0.06694403  0.31578665]
